# ==========================================
# Configuración principal de la aplicación
# ==========================================

# Nombre lógico de la aplicación Spring Boot
spring.application.name=lumen-backend

# Puerto HTTP del servidor embebido
server.port=8080

# Perfil activo por defecto para desarrollo local
spring.profiles.active=local
