# ==========================================
# Perfil PRO: configuracion para despliegue
# ==========================================

# Conexión a MySQL en entorno local
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


# HikariCP: mayor tolerancia a desconexiones intermitentes de MySQL en desarrollo
spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.max-lifetime=120000
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-test-query=SELECT 1

# Estrategia de Hibernate para desarrollo:
# update crea/actualiza tablas sin perder estructura existente cuando es posible
spring.jpa.hibernate.ddl-auto=update

# Muestra sentencias SQL en consola para depuración
spring.jpa.show-sql=true

# Formatea SQL para facilitar la lectura durante desarrollo
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# Configuración de correo (Modo Producción SSL)
# ==========================================

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=2525
spring.mail.username=xrlopruf525@ieshnosmachado.org
spring.mail.password=xsmtpsib-876af34f9b16639aa820244bbf432df338bdd947b45c6e9b362a4edc308362fe-VKvVcwMBdCyggPnS
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=*